### ISSUE TITLE
same issue, stuck at 1.55%

### ISSUE THREAD

**Issue by foxjazz** [mayuso/PNGToSVG#4] opened 2022-05-20 03:23 UTC
<img width="1152" alt="test" src="https://user-images.githubusercontent.com/867496/169444158-310d05c4-156d-4c5c-abf3-5512186e2a0b.png">

**Comment by mayuso** [comment] 2022-05-20 22:22
It's not stuck, it just takes a lot of time on some images for some reason. Thank you for your report, but as I mentioned in the other issue, I already abandoned this project and currently work on new ones, so I don't really have the time to optimize these problems.

Please fill free to develop an optimization that works and I will gladly merge your contributions to the project.

**Comment by mayuso** [comment] 2022-05-20 22:22
Duplicate of #3

**Closed by mayuso** 2022-05-20 22:22 UTC
